name: Test Compatibility

on: 
  workflow_dispatch:
  push:

jobs:
  call-test-compatibility:
    uses: lacework/oss-actions/.github/workflows/tf-test-compatibility.yml@main
    secrets: inherit
    with:
      trigger-release: false 