name: Test Compatibility

on: 
  workflow_dispatch:
  issue_comment:                                     
    types: [created, edited]


jobs:
  call-nightly-workflow:
    if: contains(github.event.comment.html_url, '/pull/') &&  contains(github.event.comment.body, 'make it so') 
    uses: lacework/oss-actions/.github/workflows/tf-test-compatibility.yml@main
    secrets: inherit
